### ISSUE TITLE
HAProxy Helm Chart does not supports new version haproxy-enterprise

### ISSUE THREAD

**Issue by Infusible** [haproxytech/helm-charts#110]
We used HAProxy Helm Chart and hapee version 2.2r1(docker container image), but can not upgrade, because  new version hapee 2.4.r1
https://www.haproxy.com/documentation/hapee/latest/getting-started/installation/docker/

In new version used s6-overlay, and runs HAProxy Enterprise and the HAProxy Data Plane API as services

**Comment by dkorunic** [comment]
@Infusible This has been resolved in release [1.7.1](https://github.com/haproxytech/helm-charts/releases/tag/haproxy-1.7.1) of haproxy Chart. However due to technical complexities, Chart for HAProxy CE will work out of the box, while EE images require the following in values override:

```
args:
  enabled: false
```

Reason for that is that by default S6 overlay (that's active in EE images) uses any CMD arguments that are being passed to container so we have to disable that.
