### ISSUE TITLE
 http/3 QUIC protocols require UDP ports

### ISSUE THREAD

**Issue by sharifm-informatica** [haproxytech/helm-charts#159]
Starting with haproxy 2.6 http/3 and QUIC are supported. To support http/3 QUIC protocols, the haproxy service has to  listen on UDP in ports not just TCP. The chart appears to support TCP only.

**Comment by dkorunic** [comment]
@sharifm-informatica This is sadly not correct. QUIC support is experimental and it requires experimental OpenSSL (as in non-distro, non-standard fork) that isn't available in any distribution yet. Therefore our haproxytech Docker builds don't build with nonstandard OpenSSL and don't support QUIC yet, since we that would impact many unsuspecting users that don't want/need unsupported OpenSSL forks. At some future point this might change and we could start supporting GnuTLS, but that is still work in progress.
Therefore there is nothing to add to this chart, yet.

**Comment by sharifm-informatica** [comment]
You are absolutely correct. This may be too early for this request. Thank you
