### ISSUE TITLE
Health Checks with multiple replicas

### ISSUE THREAD

**Issue by rarecrumb** [haproxytech/helm-charts#187]
When using health checks on backend services, does the number of replicas come into play?

Example:
```yaml
default-server check inter 30s fall 1 rise 1 init-addr libc,none observe layer7 error-limit 2 on-error mark-down
```

If I'm running 3 replicas, and my clients are connect to the HAProxy service (with those 3 replicas behind the service object), does that mean this health check needs to fail 2 * N number of replicas before the backend is taken out of rotation?

**Comment by dkorunic** [comment]
Hi, Ingress-specific questions should be sent to [Kubernetes Ingress ](https://github.com/haproxytech/kubernetes-ingress/issues) project issue tracker since this is a separate project with issue tracker related just to Helm Chart issues, but let me answer here: Ingress Controller instances don't synchronise their states and/or backend status between themselves by default. Each instance decides on backend status on its own.

**Comment by rarecrumb** [comment]
> Hi, Ingress-specific questions should be sent to [Kubernetes Ingress ](https://github.com/haproxytech/kubernetes-ingress/issues) project issue tracker since this is a separate project with issue tracker related just to Helm Chart issues, but let me answer here: Ingress Controller instances don't synchronise their states and/or backend status between themselves by default. Each instance decides on backend status on its own.

I'm not using Ingress, I'm just using HAProxy pods as an internal service.

**Comment by ivanmatmati** [comment]
Hi @rarecrumb , it doesn't matter. Whatever the use case, the haproxy instances don't communicate their status information to each other. Consider them as isolated as possible.
