### ISSUE TITLE
crdjob-1 : ttlSecondAfterFinish property delete the job after 120 seconds

### ISSUE THREAD

**Issue by xaviernouaille** [haproxytech/helm-charts#214]
Hi,
I use your helm chart, version 1.33.1. I use argocd to manage my kubernetes cluster
The job haproxy-ingress-private-crdjob-1 that is created has a ttlSecondAfterFinish, which will completely delete the job after 120 seconds. This causes an issue with Argo's synchronization as it immediately goes out of sync.

![screencapture-argocd-bender-dial-once-applications-haproxy-ingress-private-production-2023-12-20-14_41_10](https://github.com/haproxytech/helm-charts/assets/68466322/684d8c55-9f8c-4cf9-80f9-6f3e9b5b4c22)

How can I resolve this problem so that my application can return to a Healthy status?

**Comment by dkorunic** [comment]
[The bug is in ArgoCD](https://github.com/argoproj/argo-cd/discussions/8247) and while we understand that this might be a blocker for you, we have strong reasons for not using hooks due to compatibility with systems that don't use Hooks (such as AWS Container Marketplace). You should implore ArgoCD team to fix the issue.

**Comment by xaviernouaille** [comment]
Is there no property that would allow me to reload the configuration and remove this ttl? THANKS.

**Comment by dkorunic** [comment]
There is no property to do this intentionally. This works as intended and cleanup is intended feature.

**Comment by dkorunic** [comment]
Fix incoming in https://github.com/haproxytech/helm-charts/commit/f5f2e7389e31fcbc7c1ceefa09fed46732b4f6ee.
