### ISSUE TITLE
Allow setting pod security-context in kubernetes-ingress for rootless 80/443

### ISSUE THREAD

**Issue by vaskozl** [haproxytech/helm-charts#241]
Kubernetes now allows setting certain sysctls which allows one to run the controller on ports 80/443 without priveleged/root.

However the chart does not allow configuring the security context and doesn't set the sysctl by default either:
```
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "80"
```

Furthermore the privileged busybox workaround that is suggested is now generally no longer required.

**Comment by dkorunic** [comment]
Sadly `net.ipv4.ip_unprivileged_port_start` doesn't work everywhere either -- it both requires K8s `1.22` and at minimum Linux kernel `4.11`. We can add toggle for this in case of unprivileged containers, but it's both not a universal solution nor it should be really required any more since we bind container ports to unprivileged tcp/8080 and tcp/8443.

**Comment by vaskozl** [comment]
Both pretty old at this point but I agree that it definitely shouldn't be a default. I think simply allowing users to set securityContext themselves would suffice (let users chose the starting port e.g. 22 if ssh is forwarded) and can cover other niche use cases that might need some custom sysctls.

**Comment by dkorunic** [comment]
Resolved in https://github.com/haproxytech/helm-charts/commit/3faad4879185ab1768243b6272b00ac1b7a4604b with `controller.allowPrivilegedPorts` tunable.
