### ISSUE TITLE
[kubernetes-ingress] Allow more CRD job pod customizations

### ISSUE THREAD

**Issue by vholer** [haproxytech/helm-charts#267]
As part of #264 , additional CRD job pod annotations and TTL were already introduced.

It would be nice if also other pod parameters (like resources, tolerations and affinity) could be customized. Especially resources for job should be completely different to what is required for running controller + HAProxy.

**Comment by dkorunic** [comment]
Hi @vholer, resources, tolerations and affinity in general should be identical to regular IC pods because for simplicity we are reusing the same IC Pod. This specifically means that Pod is running with s6, HAProxy and Ingress Controller with full configuration which might be not lightweight (especially for Enterprise Edition) and that's why we kept the same Pod parameters which are known to work for full product.

**Comment by dkorunic** [comment]
As explained above, it will exactly use the same amount of resources as any other pod serving hundreds of live sites. Right now all s6 services start up by default, which means that both HAPEE/HAProxy and Ingress Controller process will start, with full configurations (maxconns, SSL cache, pools, all modules and everything else) and allowing users to downsize and/or play with specific settings is possibly harmful, since it could impact CRD job which is imperative to work properly (ie. that it has enough resources).
We understand your request, but for now this won't be implemented as requested, sorry about that.
