### ISSUE TITLE
[kubernetes-ingress] extraVolumes and extraVolumeMounts for main container

### ISSUE THREAD

**Issue by tbnguyen1407** [haproxytech/helm-charts#48]
**Problem**

kubernetes-ingress helm chart does not expose extraVolumes and extraVolumeMounts for main container. This makes it not possible to run in cluster with readOnlyRootFilesystem as directories are not writable and need to be mounted with emptyDir volume

* /etc/haproxy
* /tmp
* /var/state/haproxy

Current chart includes extraVolumes but it's only for extra containers

**Solution**

expose extraVolumes and extraVolumeMounts for main container

**Comment by dkorunic** [comment]
Resolved with commit https://github.com/haproxytech/helm-charts/commit/3aa2b73baf9ebe193edff2c88806d932f601aadf and with release https://github.com/haproxytech/helm-charts/releases/tag/kubernetes-ingress-1.12.0. Note that initially using `/etc/haproxy` as _emptyDir_ volume will cause all 1.5.1+ Controllers to panic due to missing `/etc/haproxy/haproxy.cfg` file, but we plan to address this in a future release with embedding of a default `haproxy.cfg`. CC @oktalz

**Comment by mecampbellsoup** [comment]
How would I use this to mount e.g. a custom lua plugin that I wrote?

I want to be able to use some plugin in my lua configuration. Would I have to copy-paste the entire contents of my plugin as binary or something? Should I use a PVC or ConfigMap, and then refer to that [here](https://github.com/haproxytech/helm-charts/commit/3aa2b73baf9ebe193edff2c88806d932f601aadf#diff-3824aec2faa0ade22075391132297de8b0ee57b8d89c097ead844020022e23baR374)?

The dots are not quite clicking for me on this, any help is appreciated!

@dkorunic @tbnguyen1407 🙏
