### ISSUE TITLE
cannot start the ingress as loadbalancer instead of NodePort

### ISSUE THREAD

**Issue by rdupas** [haproxytech/helm-charts#61]
Hello,

I am setting up a cluster on bare metal and based on the documentation it should be possible to have ha proxy as the ingress controller without using NodePort.
I want ha proxy to bind to the host's port 80 and 443

I am running the following command to do so:
```
$helm install haproxy-controller --namespace haproxy-controller -f haproxy-ingress-values.yaml haproxytech/kubernetes-ingress --set service.type=LoadBalancer --set kind=DaemonSet
```
but getting the following result:
```
NAME: haproxy-controller
LAST DEPLOYED: Sun Mar 14 17:01:29 2021
NAMESPACE: haproxy-controller
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
HAProxy Kubernetes Ingress Controller has been successfully installed.

Controller image deployed is: "haproxytech/kubernetes-ingress:1.5.3".
Your controller is of a "Deployment" kind. Your controller service is running as a "NodePort" type.
```
even with the override of the service type it is still spinning up as node port.
Am I missing something?

please advise

**Comment by dkorunic** [comment]
Hi @rdupas , parameters used do not match the hierarchy which we expect, see more in Helm Chart [Readme](https://github.com/haproxytech/helm-charts/blob/master/kubernetes-ingress/README.md) and [values](https://github.com/haproxytech/helm-charts/blob/master/kubernetes-ingress/values.yaml) definitions. Namely, you have to set service type with `--set controller.service.type=LoadBalancer` and kind with `--set controller.kind=DaemonSet`, otherwise it would be unclear if it is related to controller, service, default backend, etc.

**Comment by rdupas** [comment]
Thanks @dkorunic  for the quick response.

the ingress starts correctly with the correct values:
```
helm install haproxy-controller --namespace haproxy-controller haproxytech/kubernetes-ingress --set controller.service.type=LoadBalancer --set controller.kind=DaemonSet --set controller.daemonset.useHostPort=true --set controller.daemonset.useHostNetwork=true
NAME: haproxy-controller
LAST DEPLOYED: Sun Mar 14 18:02:12 2021
NAMESPACE: haproxy-controller
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
HAProxy Kubernetes Ingress Controller has been successfully installed.

Controller image deployed is: "haproxytech/kubernetes-ingress:1.5.3".
Your controller is of a "DaemonSet" kind. Your controller service is running as a "LoadBalancer" type. 
```
