### ISSUE TITLE
Protect stats page with basic auth

### ISSUE THREAD

**Issue by guanzo** [haproxytech/helm-charts#64]
Hi, the routes my HAProxy serves are all public, but I want the stats page behind basic auth.

Seems like all I need is this config

```
frontend stats
 # other default config
  stats auth hi:mom
```

but i can't find a way to get my `stats auth hi:mom` config there? There's a `global-config-snippet`, `backend-config-snippet`, but no `frontend-config-snippet`.

HAProxy errors when I put `stats auth hi:mom` in the `global-config-snippet`.

**Comment by dkorunic** [comment]
Dear @guanzo , this is not yet supported but developers are confirming that it's can be easily done in no time. Please open a corresponding ticket in HAProxy [Ingress Controller](https://github.com/haproxytech/kubernetes-ingress) project, since issues opened here relate only to Helm Chart and its development -- discussion and feature requests for Ingress Controller belong to a separate project.
