### ISSUE TITLE
Document changes

### ISSUE THREAD

**Issue by benzman81** [haproxytech/helm-charts#83]
It would be nice, to have a changelog for the helm charts or document its changes in the release page.
 
Currently, we have Kubernetes-Ingress installed in version 1.12.1 and see that there is an upgrade available for 1.15.1 but we don't know the changes and if or how it affects our setup.

**Comment by dkorunic** [comment]
@benzman81 Helm Charts releases are managed through chart-releaser who, sadly, doesn't have the ability to aggregate and pull Git changelogs since last release. It is of course possible to browse through Git log, all our commit messages document what's been done.
In regards to Ingress Controller itself (who has major and relevant changes, possibly more breaking than a Helm Chart), changelogs are published with each release: https://github.com/haproxytech/kubernetes-ingress/releases/
