### ISSUE TITLE
Namespace over ride in values.yaml

### ISSUE THREAD

**Issue by Daxcor69** [haproxytech/helm-charts#98]
Is it possible to put a namespace over ride in the values.yaml file  in stead of  on the install command line?

thanks
Brad

**Comment by dkorunic** [comment]
@Daxcor69 Reason why we don't do this is because Helm itself uses namespace argument for install, uninstall etc. to be able to create and delete objects like a K8s package manager. If we were to put namespace into overrides, it would create a confusion where objects could remain after uninstallation and create a permanent conflict for reinstallation and/or upgrade.
